---
title: "Other maps"
author: "Carmen Rodriguez Cabrera"
date: "2/26/2022"
output: pdf_document
---
```{r message=FALSE, warning=FALSE, include=FALSE}
#--------------Load the tidycensus package into your R session-----------------
library(tidycensus)
library(tidyverse)
library(Hmisc)
library(reshape2)
library(ggplot2)
library(sf)
library(tigris)
library(crsuggest)

# Define your Census API key and set it with census_api_key()
census_api_key("db6e734054a38a24963f654c19b83e7ffca8dd0f", install = TRUE, overwrite = TRUE) #only need to run once

readRenviron("~/.Renviron") #run this to use  API key

#Check API key
Sys.getenv("CENSUS_API_KEY")
```


```{r,cache =TRUE}
options(tigris_use_cache = TRUE)
#2006-2010
vars<-c(`High school graduate or higher` = "DP02_0066P",
                 `Bachelors degree or higher` = "DP02_0067P",
                 `Below Poverty Line` = "DP03_0119P")
  
options(tigris_use_cache = TRUE) 
demographics_2010<-get_acs(state = "MA", geography = "tract", 
                  variables = vars, year = 2010, geometry = TRUE)  


#quick extraction to make the optimal care map
acstigris<-get_acs(state = "MA", geography = "tract", 
                  variables = "DP02_0066P", year = 2019, geometry = TRUE)


# demographics_2010 %>% filter(variable== "Median Income") %>% ggplot(aes(fill = estimate)) + 
#   geom_sf(color = NA) + 
#   coord_sf(crs = 6491, datum = NA) +
#   scale_fill_viridis_c(option = "C",direction = 1) +
#   labs(title = "Median Income Distribution by Census Tracts in MA",
#        caption = "Data source: 2006-2010 5-year ACS",
#        fill = "Estimate") + theme_minimal()

demographics_2010 %>% filter(variable %in% c("High school graduate or higher","Bachelors degree or higher")) %>% ggplot(aes(fill = estimate)) + 
  facet_wrap(~ variable) +                            
  geom_sf(color = NA) + 
  coord_sf(crs = 6491, datum = NA) +
  scale_fill_viridis_c(option = "C",direction = 1) +
  labs(title = "Educational Attainment by Census Tracts in MA",
       caption = "Data source: 2006-2010 5-year ACS",
       fill = "Percentage") + theme_minimal()

demographics_2010 %>% filter(variable==c("Below Poverty Line")) %>% ggplot(aes(fill = estimate)) + 
  geom_sf(color = NA) + 
  coord_sf(crs = 6491, datum = NA) +
  scale_fill_viridis_c(option = "C",direction = 1) +
  labs(title = "Families and people whose income is below poverty level by Census Tracts in MA",
       caption = "Data source: 2006-2010 5-year ACS",
       fill = "Percentage") + theme_minimal()
```

```{r,cache =TRUE}
#2011-2015
options(tigris_use_cache = TRUE)
demographics_2015<-get_acs(state = "MA", geography = "tract", 
                  variables = vars, year = 2015, geometry = TRUE) 


# demographics_2015 %>% filter(variable== "Median Income") %>% ggplot(aes(fill = estimate)) + 
#   geom_sf(color = NA) + 
#   coord_sf(crs = 6491, datum = NA) +
#   scale_fill_viridis_c(option = "C",direction = 1) +
#   labs(title = "Median Income Distribution by Census Tracts in MA",
#        caption = "Data source: 2011-2015 5-year ACS",
#        fill = "Estimate") + theme_minimal()


demographics_2015 %>% filter(variable %in% c("High school graduate or higher","Bachelors degree or higher")) %>% ggplot(aes(fill = estimate)) + 
  facet_wrap(~ variable) +                            
  geom_sf(color = NA) + 
  coord_sf(crs = 6491, datum = NA) +
  scale_fill_viridis_c(option = "C",direction = 1) +
  labs(title = "Educational Attainment by Census Tracts in MA",
       caption = "Data source: 2011-2015 5-year ACS",
       fill = "Percentage") + theme_minimal()

demographics_2015 %>% filter(variable==c("Below Poverty Line")) %>% ggplot(aes(fill = estimate)) + 
  geom_sf(color = NA) + 
  coord_sf(crs = 6491, datum = NA) +
  scale_fill_viridis_c(option = "C",direction = 1) +
  labs(title = "Families and people whose income is below poverty level by Census Tracts in MA",
       caption = "Data source: 2011-2015 5-year ACS",
       fill = "Percentage") + theme_minimal()


```

```{r,cache =TRUE}
#2015-2019
vars1<-c(`High school graduate or higher` = "DP02_0067P",
                 `Bachelors degree or higher` = "DP02_0068P",
                 `Below Poverty Line` = "DP03_0119P",
                  `Renter Occupied Housing` = "DP04_0047P",
                   `Owner Occupied Housing` = "DP04_0046P")
  
options(tigris_use_cache = TRUE) 
demographics_2019<-get_acs(state = "MA", geography = "tract", 
                  variables = vars1, year = 2019, geometry = TRUE)

# demographics_2019 %>% filter(variable== "Median Income") %>% ggplot(aes(fill = estimate)) + 
#   geom_sf(color = NA) + 
#   coord_sf(crs = 6491, datum = NA) +
#   scale_fill_viridis_c(option = "C",direction = 1) +
#   labs(title = "Median Income Distribution by Census Tracts in MA",
#        caption = "Data source: 2015-2019 5-year ACS",
#        fill = "Estimate") + theme_minimal()

demographics_2019 %>% filter(variable %in% c("High school graduate or higher","Bachelors degree or higher")) %>% ggplot(aes(fill = estimate)) + 
  facet_wrap(~ variable) +                            
  geom_sf(color = NA) + 
  coord_sf(crs = 6491, datum = NA) +
  scale_fill_viridis_c(option = "C",direction = 1) +
  labs(title = "Educational Attainment by Census Tracts in MA",
       caption = "Data source: 2015-2019 5-year ACS",
       fill = "Percentage") + theme_minimal()

demographics_2019 %>% filter(variable==c("Below Poverty Line")) %>% ggplot(aes(fill = estimate)) + 
  geom_sf(color = NA) + 
  coord_sf(crs = 6491, datum = NA) +
  scale_fill_viridis_c(option = "C",direction = 1) +
  labs(title = "Families and people whose income is below poverty level by Census Tracts in MA",
       caption = "Data source: 2015-2019 5-year ACS",
       fill = "Percentage") + theme_minimal()

demographics_2019 %>% filter(variable %in% c("Renter Occupied Housing","Owner Occupied Housing")) %>% 
  ggplot(aes(fill = estimate)) +  
  facet_wrap(~ variable) +
  geom_sf(color = NA) + 
  coord_sf(crs = 6491, datum = NA) +
  scale_fill_viridis_c(option = "C",direction = 1) +
  labs(title = "Housing tenure by Census Tracts in MA",
       caption = "Data source: 2015-2019 5-year ACS",
       fill = "Percentage") + theme_minimal()

```

